"""fix

Revision ID: 436ee4cef87e
Revises: 9e2ddb6e0d14
Create Date: 2019-11-02 13:20:11.526602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436ee4cef87e'
down_revision = '9e2ddb6e0d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'id')
    # ### end Alembic commands ###
