"""add dialog

Revision ID: 4c7140d02124
Revises: c9379689cd27
Create Date: 2019-12-05 23:50:51.814144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7140d02124'
down_revision = 'c9379689cd27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delete_first', sa.Boolean(), nullable=True),
    sa.Column('delete_second', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_dialog',
    sa.Column('id_first', sa.Integer(), nullable=True),
    sa.Column('id_second', sa.Integer(), nullable=True),
    sa.Column('id_dialog', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dialog'], ['dialog.id'], ),
    sa.ForeignKeyConstraint(['id_first'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_second'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_dialog')
    )
    op.add_column('association_messages', sa.Column('id_dialog', sa.Integer(), nullable=True))
    op.drop_constraint('association_messages_id_recipient_fkey', 'association_messages', type_='foreignkey')
    op.create_foreign_key(None, 'association_messages', 'dialog', ['id_dialog'], ['id'])
    op.drop_column('association_messages', 'id_recipient')
    op.add_column('message', sa.Column('sender', sa.Integer(), nullable=False))
    op.drop_index('ix_message_id', table_name='message')
    op.create_foreign_key(None, 'message', 'user', ['sender'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_index('ix_message_id', 'message', ['id'], unique=False)
    op.drop_column('message', 'sender')
    op.add_column('association_messages', sa.Column('id_recipient', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'association_messages', type_='foreignkey')
    op.create_foreign_key('association_messages_id_recipient_fkey', 'association_messages', 'user', ['id_recipient'], ['id'])
    op.drop_column('association_messages', 'id_dialog')
    op.drop_table('association_dialog')
    op.drop_table('dialog')
    # ### end Alembic commands ###
