"""empty message

Revision ID: 5a23330bb69f
Revises: 9bcbaba5fd42
Create Date: 2019-12-09 15:37:32.388132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a23330bb69f'
down_revision = '9bcbaba5fd42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialog', sa.Column('id_user_first', sa.Integer(), nullable=True))
    op.add_column('dialog', sa.Column('id_user_second', sa.Integer(), nullable=True))
    op.drop_constraint('dialog_user_second_fkey', 'dialog', type_='foreignkey')
    op.drop_constraint('dialog_user_first_fkey', 'dialog', type_='foreignkey')
    op.create_foreign_key('user_second', 'dialog', 'user', ['id_user_second'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_first', 'dialog', 'user', ['id_user_first'], ['id'], ondelete='CASCADE')
    op.drop_column('dialog', 'user_second')
    op.drop_column('dialog', 'user_first')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialog', sa.Column('user_first', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dialog', sa.Column('user_second', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('user_first', 'dialog', type_='foreignkey')
    op.drop_constraint('user_second', 'dialog', type_='foreignkey')
    op.create_foreign_key('dialog_user_first_fkey', 'dialog', 'user', ['user_first'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('dialog_user_second_fkey', 'dialog', 'user', ['user_second'], ['id'], ondelete='CASCADE')
    op.drop_column('dialog', 'id_user_second')
    op.drop_column('dialog', 'id_user_first')
    # ### end Alembic commands ###
