"""empty message

Revision ID: 919f4d34e519
Revises: 5a23330bb69f
Create Date: 2019-12-10 09:56:47.657771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '919f4d34e519'
down_revision = '5a23330bb69f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_messages')
    op.drop_table('dialog')
    op.drop_table('association_dialog')
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('message_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sender', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sender'], ['user.id'], name='message_sender_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='message_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('association_dialog',
    sa.Column('id_first', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_second', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_dialog', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_dialog'], ['dialog.id'], name='association_dialog_id_dialog_fkey'),
    sa.ForeignKeyConstraint(['id_first'], ['user.id'], name='association_dialog_id_first_fkey'),
    sa.ForeignKeyConstraint(['id_second'], ['user.id'], name='association_dialog_id_second_fkey'),
    sa.PrimaryKeyConstraint('id_dialog', name='association_dialog_pkey')
    )
    op.create_table('dialog',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('dialog_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('delete_first', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('delete_second', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id_user_first', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_user_second', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_user_first'], ['user.id'], name='user_first', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user_second'], ['user.id'], name='user_second', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dialog_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('association_messages',
    sa.Column('id_message', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_dialog', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_dialog'], ['dialog.id'], name='association_messages_id_dialog_fkey'),
    sa.ForeignKeyConstraint(['id_message'], ['message.id'], name='association_messages_id_message_fkey'),
    sa.PrimaryKeyConstraint('id_message', name='association_messages_pkey')
    )
    # ### end Alembic commands ###
