"""empty message

Revision ID: 9bcbaba5fd42
Revises: 52a16355039d
Create Date: 2019-12-09 15:23:14.952476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcbaba5fd42'
down_revision = '52a16355039d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_messages_id_sender_fkey', 'association_messages', type_='foreignkey')
    op.drop_column('association_messages', 'id_sender')
    op.add_column('dialog', sa.Column('user_first', sa.Integer(), nullable=True))
    op.add_column('dialog', sa.Column('user_second', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dialog', 'user', ['user_first'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dialog', 'user', ['user_second'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dialog', type_='foreignkey')
    op.drop_constraint(None, 'dialog', type_='foreignkey')
    op.drop_column('dialog', 'user_second')
    op.drop_column('dialog', 'user_first')
    op.add_column('association_messages', sa.Column('id_sender', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('association_messages_id_sender_fkey', 'association_messages', 'user', ['id_sender'], ['id'])
    # ### end Alembic commands ###
