"""empty message

Revision ID: d76a8f6adad9
Revises: 
Create Date: 2019-11-02 11:50:14.977906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76a8f6adad9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dislikes_id_publication_fkey', 'dislikes', type_='foreignkey')
    op.drop_constraint('dislikes_id_user_fkey', 'dislikes', type_='foreignkey')
    op.create_foreign_key(None, 'dislikes', 'publication', ['id_publication'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dislikes', 'user', ['id_user'], ['id'], ondelete='CASCADE')
    op.drop_constraint('likes_id_publication_fkey', 'likes', type_='foreignkey')
    op.drop_constraint('likes_id_user_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'publication', ['id_publication'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'likes', 'user', ['id_user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_id_user_fkey', 'likes', 'user', ['id_user'], ['id'])
    op.create_foreign_key('likes_id_publication_fkey', 'likes', 'publication', ['id_publication'], ['id'])
    op.drop_constraint(None, 'dislikes', type_='foreignkey')
    op.drop_constraint(None, 'dislikes', type_='foreignkey')
    op.create_foreign_key('dislikes_id_user_fkey', 'dislikes', 'user', ['id_user'], ['id'])
    op.create_foreign_key('dislikes_id_publication_fkey', 'dislikes', 'publication', ['id_publication'], ['id'])
    # ### end Alembic commands ###
