"""empty message

Revision ID: e761ddf092f6
Revises: c8b22ca95a34
Create Date: 2019-10-31 13:59:25.889003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e761ddf092f6'
down_revision = 'c8b22ca95a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associate_subscriptions',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('subscription_obj_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subscription_obj_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('subscriber_id', 'subscription_obj_id')
    )
    op.drop_table('subscribers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('subscriber_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscription_obj_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], name='subscribers_subscriber_id_fkey'),
    sa.ForeignKeyConstraint(['subscription_obj_id'], ['user.id'], name='subscribers_subscription_obj_id_fkey'),
    sa.PrimaryKeyConstraint('subscriber_id', 'subscription_obj_id', name='subscribers_pkey')
    )
    op.drop_table('associate_subscriptions')
    # ### end Alembic commands ###
